id: A39D88B28
title: f839A
type: translation
source_metadata:
  languages:
  - sa
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 16:58:00.499323
  last_modified_at: 2022-05-27 16:58:00.499327
